[container.image]
repository="co528_shehan" # Docker hub name
name="ballerina_resturant" # container name
tag="v0.1.0"

[settings]
buildImage=true # you can make this false if you don't want to build the image and you just need the Dockerfile